"""Command-line interface.

lbolab run deals/helios_carveout.yaml --out reports/helios
lbolab demo --example apex --out reports/apex
lbolab screen --tickers HRB KMB SJM --target-irr 0.20 --out reports/screen
lbolab validate --out docs/VALIDATION.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

from .assumptions import Deal
from .examples import EXAMPLES
from .pipeline import AnalysisConfig, DealAnalysis, run_analysis
from .report import write_report
from .screener import ScreenAssumptions, build_deal, fetch_company, screen_companies
from .validation import run_validation, to_markdown


def _index_levels(annual_return: float, hold_years: int) -> tuple[float, ...]:
    return tuple(float((1.0 + annual_return) ** year) for year in range(hold_years + 1))


def _write_outputs(analysis: DealAnalysis, out: Path, screen: pd.DataFrame | None = None, target_irr: float = 0.20) -> None:
    out.mkdir(parents=True, exist_ok=True)
    analysis.result.schedule.to_csv(out / "model_schedule.csv", index=False)
    analysis.bridge.to_frame().to_csv(out / "value_bridge.csv", index=False)
    analysis.levers.to_csv(out / "levers.csv", index=False)
    if analysis.monte_carlo is not None:
        analysis.monte_carlo.trials.to_csv(out / "monte_carlo_trials.csv", index=False)
    if screen is not None:
        screen.to_csv(out / "screen.csv", index=False)
    path = write_report(analysis, out, screen=screen, target_irr=target_irr)
    print(f"Report: {path.resolve()}")


def _analysis_config(args: argparse.Namespace, deal: Deal) -> AnalysisConfig:
    return AnalysisConfig(
        monte_carlo_trials=args.trials,
        run_monte_carlo=not args.no_monte_carlo,
        run_leverage_curve=not args.no_leverage_curve,
        leverage_curve_trials=max(args.trials // 5, 100),
        index_levels=_index_levels(args.index_return, deal.exit.hold_years) if args.index_return else (),
    )


def cmd_run(args: argparse.Namespace) -> None:
    deal = Deal.from_yaml(args.deal)
    print(
        f"{deal.name}: {deal.exit.entry_multiple:.1f}x entry, {deal.total_debt_turns():.2f}x leverage, "
        f"{deal.exit.hold_years}-year hold"
    )
    analysis = run_analysis(deal, _analysis_config(args, deal))
    _write_outputs(analysis, Path(args.out))


def cmd_demo(args: argparse.Namespace) -> None:
    deal = EXAMPLES[args.example]()
    print(f"Running the bundled example: {deal.name}")
    analysis = run_analysis(deal, _analysis_config(args, deal))
    _write_outputs(analysis, Path(args.out))


def cmd_screen(args: argparse.Namespace) -> None:
    print(f"Screening {len(args.tickers)} companies for a {100 * args.target_irr:.0f}% IRR take-private ...")
    assumptions = ScreenAssumptions(leverage_turns=args.leverage, hold_years=args.hold_years)
    screen = screen_companies(args.tickers, assumptions, args.target_irr)
    columns = [
        c for c in ("ticker", "name", "ev_ebitda", "financeable_leverage", "irr_at_market_price", "max_premium") if c in screen
    ]
    with pd.option_context("display.width", 200, "display.max_columns", 20):
        print(screen[columns].to_string(index=False))

    best = screen[screen["max_premium"].notna()] if "max_premium" in screen else pd.DataFrame()
    if best.empty:
        print("No company in the list clears the hurdle at any premium.")
        return
    leader = best.iloc[0]
    print(f"Modelling the most attractive candidate in full: {leader['ticker']}")
    company = fetch_company(str(leader["ticker"]))
    example = build_deal(
        company, float(leader["max_premium"]), ScreenAssumptions(leverage_turns=float(leader["financeable_leverage"]))
    )
    analysis = run_analysis(example, _analysis_config(args, example))
    _write_outputs(analysis, Path(args.out), screen=screen, target_irr=args.target_irr)


def cmd_validate(args: argparse.Namespace) -> None:
    results = run_validation()
    table = to_markdown(results)
    print(table)
    if args.out:
        from datetime import datetime, timezone

        header = (
            "# Validation report\n\n"
            f"Generated by `lbolab validate` on {datetime.now(timezone.utc):%Y-%m-%d}. Every accounting identity and "
            "return calculation is checked against an independent computation or a closed-form result.\n\n"
        )
        Path(args.out).write_text(header + table + "\n", encoding="utf-8")
    if not results["passed"].all():
        sys.exit(1)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="lbolab", description="Leveraged buyout modelling and return attribution.")
    sub = parser.add_subparsers(dest="command", required=True)

    def analysis_flags(target: argparse.ArgumentParser, default_out: str) -> None:
        target.add_argument("--out", default=default_out)
        target.add_argument("--trials", type=int, default=2000, help="Monte Carlo trials")
        target.add_argument("--no-monte-carlo", action="store_true")
        target.add_argument("--no-leverage-curve", action="store_true")
        target.add_argument(
            "--index-return",
            type=float,
            default=0.09,
            help="annual public index return used for the PME comparison; 0 disables it",
        )

    run = sub.add_parser("run", help="analyse a deal defined in YAML")
    run.add_argument("deal")
    analysis_flags(run, "reports/deal")
    run.set_defaults(func=cmd_run)

    demo = sub.add_parser("demo", help="analyse a bundled example deal")
    demo.add_argument("--example", choices=sorted(EXAMPLES), default="helios")
    analysis_flags(demo, "reports/demo")
    demo.set_defaults(func=cmd_demo)

    screen = sub.add_parser("screen", help="screen listed companies for take-private capacity")
    screen.add_argument("--tickers", nargs="+", required=True)
    screen.add_argument("--target-irr", type=float, default=0.20)
    screen.add_argument("--leverage", type=float, default=5.0)
    screen.add_argument("--hold-years", type=int, default=5)
    analysis_flags(screen, "reports/screen")
    screen.set_defaults(func=cmd_screen)

    validate = sub.add_parser("validate", help="run the numerical and accounting validation suite")
    validate.add_argument("--out", default=None)
    validate.set_defaults(func=cmd_validate)
    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    np.seterr(all="ignore")
    args.func(args)


if __name__ == "__main__":
    main()
